pipeline{
    agent any
    {
        stages
        {
        stage
            {
                steps('Initilaize')
                {
                    echo "====++++something++++===="
                }
            }
        stage
            {
                steps('bulid')
                {
                    echo " my bulid"
                }
            }
        }
    }
            