pipeline {
    agent any
    stages {
        stage ('Build Servlet Project') {
            steps {
                /*For windows machine */
               bat  'mvn -f webproj/pom.xml clean package'
 
                /*For Mac & Linux machine */
               // sh  'mvn clean package'
            }
 
            post{
                success{
                    echo 'Now Archiving ....'
 
                    archiveArtifacts artifacts : '**/*.war'
                }
            }
        }
        stage('deploy in staging area')
        {
            steps
            {
                build job : 'deploy_stagingarea_pipelinecode'
            }
        }
    }
}